---

- name: restart application
  systemd:
    name: playreading.service
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: fix selinux permissions
  command: restorecon -R /var/www/playreading
