---

- name: reload firewalld
  systemd:
    name: firewalld.service
    state: reloaded

- name: enable quic in selinux
  shell: |
    semanage port -D
    semanage port -a -t http_port_t -p udp 443
